title: "The Auri Manifesto"
description: "Value Without Noise."
theme: jekyll-theme-cayman
show_downloads: false
github:
  is_project_page: true
  repository_url: https://github.com/auricorelabs/auri-manifesto
  owner_name: Auricore Labs
  owner_url: https://github.com/auricorelabs
